### ISSUE TITLE
Document if storage of value should be pinned?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Berrysoft/ClassLibrary#1]
https://github.com/Berrysoft/ClassLibrary/blob/9f6eca4029c22f3b4123d29da80894de5dead780/src/Berrysoft.Unsafe/ByReference.cs#L22

To avoid GC change location and invalidate  pointer. I guess.

**Comment by Berrysoft** [comment]
Sorry to reply so late... You're right, the value *should* be pinned, but the struct is designed for VB, which doesn't have the equivalent grammer to `ref` variables and `ref` fields in C#. Anyway, I'll add the warning to the document, thanks!

**Comment by dzmitry-lahoda** [comment]
That code allows to store ref inside struct. May be usefull for ECS systems in gamedev. I.e. memory will not be ever reclaimed from lists but loop onto next frame.

**Comment by Berrysoft** [comment]
Good example! It seems that the usage of the struct is much more than I have thought.😄
